spring:
  application:
    name: zuul
server:
  port: 7071

# routes to serviceId


zuul:
  routes:
    payment: /api-payment/**
    user-management: /api-usermanagement/**
    ribbon: /api-ribbon/**

# routes to url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/



