server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/

logging:
  file: ./springboot-booking.log
  level: info

spring:
  application:
    name: booking
  datasource:
    url: jdbc:mysql://localhost:3306/mass_booking
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  type-aliases-package: com.hailion.mass.booking.entity
  mapper-locations: classpath:mapper/**/*.xml


