spring:
  profiles:
    active: dev

server:
  port: 8111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  type-aliases-package: com.hailion.mass.booking.entity
  mapper-locations: classpath:mapper/**/*.xml




